### ISSUE TITLE
BT is not found

### ISSUE THREAD

**Issue by uchan-nos** [hikalium/opv86#5]
I searched opv86 with "bt", but it doesn't show the mnemonic.
https://hikalium.github.io/opv86/?q=bt

It shows "btc", "btr", "bts". Only "bt" is not included in the result.

PS. Opv86 is so wonderful service for me.
Recent days I'm using it many times a day.

**Comment by hikalium** [comment]
Thanks for the report! Now BT should be shown up with the commit above.
